# Generated by Django 4.1.3 on 2022-11-27 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(choices=[('AFG', 'Afghanistan'), ('ALB', 'Albania'), ('DZA', 'Algeria'), ('FIN', 'Finland'), ('FRA', 'France'), ('DEU', 'Germany'), ('IND', 'India'), ('ITA', 'Italy'), ('MEX', 'Mexico'), ('UZB', 'Uzbekistan'), ('USA', 'United States of America')], max_length=100)),
            ],
            options={
                'verbose_name': ('author',),
                'verbose_name_plural': 'authors',
            },
        ),
        migrations.CreateModel(
            name='PublisherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(choices=[('AFG', 'Afghanistan'), ('ALB', 'Albania'), ('DZA', 'Algeria'), ('FIN', 'Finland'), ('FRA', 'France'), ('DEU', 'Germany'), ('IND', 'India'), ('ITA', 'Italy'), ('MEX', 'Mexico'), ('UZB', 'Uzbekistan'), ('USA', 'United States of America')], max_length=125)),
            ],
            options={
                'verbose_name': ('publisher',),
                'verbose_name_plural': 'publishers',
            },
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('body', models.TextField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_api.authormodel')),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_api.publishermodel')),
            ],
            options={
                'verbose_name': ('post',),
                'verbose_name_plural': 'posts',
            },
        ),
    ]
